"""Add_integration_fields

Revision ID: 31de748cb282
Revises: 001_initial
Create Date: 2026-02-04 15:01:36.696314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '31de748cb282'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aiknowledgebase', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    op.alter_column('backlogitem', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('backlogitem', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('backlogitem', 'item_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('TECHNICAL', 'FUNCTIONAL', 'PROCESS', 'TOOL', 'AI', 'OTHER', name='backlogtype'),
               existing_nullable=False,
               postgresql_using="CASE WHEN item_type = 'Technisch' THEN 'TECHNICAL'::backlogtype WHEN item_type = 'Functioneel' THEN 'FUNCTIONAL'::backlogtype ELSE 'OTHER'::backlogtype END")
    op.alter_column('backlogitem', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='backlogpriority'),
               existing_nullable=False,
               postgresql_using="CASE WHEN priority = 'Laag' THEN 'LOW'::backlogpriority WHEN priority = 'Gemiddeld' THEN 'MEDIUM'::backlogpriority WHEN priority = 'Hoog' THEN 'HIGH'::backlogpriority ELSE 'LOW'::backlogpriority END")
    op.alter_column('backlogitem', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('NEW', 'REVIEW', 'APPROVED', 'IN_PROGRESS', 'DONE', 'REJECTED', name='backlogstatus'),
               existing_nullable=False,
               postgresql_using="CASE WHEN status = 'Nieuw' THEN 'NEW'::backlogstatus WHEN status = 'Mee bezig' THEN 'IN_PROGRESS'::backlogstatus WHEN status = 'Gereed' THEN 'DONE'::backlogstatus ELSE 'NEW'::backlogstatus END")
    op.alter_column('backlogitem', 'submitter_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('backlogitem', 'admin_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('backlogitem', 'votes',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('backlogitem', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('backlogitem', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.create_foreign_key(None, 'backlogitem', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'backlogitem', 'user', ['submitted_by_id'], ['id'])
    op.add_column('incident', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incident', sa.Column('external_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incident', sa.Column('last_synced', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_incident_external_id'), 'incident', ['external_id'], unique=False)
    op.add_column('scope', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scope', sa.Column('external_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scope', sa.Column('last_synced', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_scope_external_id'), 'scope', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scope_external_id'), table_name='scope')
    op.drop_column('scope', 'last_synced')
    op.drop_column('scope', 'external_source')
    op.drop_column('scope', 'external_id')
    op.drop_index(op.f('ix_incident_external_id'), table_name='incident')
    op.drop_column('incident', 'last_synced')
    op.drop_column('incident', 'external_source')
    op.drop_column('incident', 'external_id')
    op.drop_constraint(None, 'backlogitem', type_='foreignkey')
    op.drop_constraint(None, 'backlogitem', type_='foreignkey')
    op.alter_column('backlogitem', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               nullable=True)
    op.alter_column('backlogitem', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               nullable=True)
    op.alter_column('backlogitem', 'votes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('backlogitem', 'admin_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('backlogitem', 'submitter_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('backlogitem', 'status',
               existing_type=sa.Enum('NEW', 'REVIEW', 'APPROVED', 'IN_PROGRESS', 'DONE', 'REJECTED', name='backlogstatus'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('backlogitem', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='backlogpriority'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('backlogitem', 'item_type',
               existing_type=sa.Enum('TECHNICAL', 'FUNCTIONAL', 'PROCESS', 'TOOL', 'AI', 'OTHER', name='backlogtype'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('backlogitem', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('backlogitem', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('aiknowledgebase', 'embedding')
    # ### end Alembic commands ###
