from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from uuid import UUID

from app.core.auth import CurrentUser, get_current_user, require_role
from app.core.db import get_db
from app.models.core_models import IMSKnowledgeChunk
from app.schemas.knowledge import KnowledgeChunkCreate, KnowledgeChunkUpdate, KnowledgeChunkResponse

router = APIRouter()


@router.get("/", response_model=list[KnowledgeChunkResponse])
async def list_knowledge_chunks(
    layer: str | None = None,
    tenant_id: UUID | None = None,
    source_type: str | None = None,
    source_id: UUID | None = None,
    skip: int = 0,
    limit: int = 100,
    current_user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    query = select(IMSKnowledgeChunk)
    if layer:
        query = query.where(IMSKnowledgeChunk.layer == layer)
    if tenant_id:
        query = query.where(IMSKnowledgeChunk.tenant_id == tenant_id)
    if source_type:
        query = query.where(IMSKnowledgeChunk.source_type == source_type)
    if source_id:
        query = query.where(IMSKnowledgeChunk.source_id == source_id)
    query = query.offset(skip).limit(limit)
    result = await db.execute(query)
    return result.scalars().all()


@router.get("/{chunk_id}", response_model=KnowledgeChunkResponse)
async def get_knowledge_chunk(
    chunk_id: UUID,
    current_user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(IMSKnowledgeChunk).where(IMSKnowledgeChunk.id == chunk_id)
    )
    chunk = result.scalar_one_or_none()
    if not chunk:
        raise HTTPException(status_code=404, detail="KnowledgeChunk not found")
    return chunk


@router.post("/", response_model=KnowledgeChunkResponse, status_code=201)
async def create_knowledge_chunk(
    data: KnowledgeChunkCreate,
    current_user: CurrentUser = Depends(require_role("tims_lid")),
    db: AsyncSession = Depends(get_db),
):
    # Create chunk without embedding — embedding will be generated by agent pipeline
    chunk = IMSKnowledgeChunk(
        layer=data.layer,
        tenant_id=data.tenant_id,
        source_type=data.source_type,
        source_id=data.source_id,
        chunk_index=data.chunk_index,
        content=data.content,
        model_used=data.model_used,
        embedding=[0.0] * 1536,  # placeholder zero vector
    )
    db.add(chunk)
    await db.flush()
    await db.refresh(chunk)
    return chunk


@router.patch("/{chunk_id}", response_model=KnowledgeChunkResponse)
async def update_knowledge_chunk(
    chunk_id: UUID,
    data: KnowledgeChunkUpdate,
    current_user: CurrentUser = Depends(require_role("tims_lid")),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(IMSKnowledgeChunk).where(IMSKnowledgeChunk.id == chunk_id)
    )
    chunk = result.scalar_one_or_none()
    if not chunk:
        raise HTTPException(status_code=404, detail="KnowledgeChunk not found")
    for field, value in data.model_dump(exclude_unset=True).items():
        setattr(chunk, field, value)
    await db.flush()
    await db.refresh(chunk)
    return chunk


@router.delete("/{chunk_id}", status_code=204)
async def delete_knowledge_chunk(
    chunk_id: UUID,
    current_user: CurrentUser = Depends(require_role("admin")),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(IMSKnowledgeChunk).where(IMSKnowledgeChunk.id == chunk_id)
    )
    chunk = result.scalar_one_or_none()
    if not chunk:
        raise HTTPException(status_code=404, detail="KnowledgeChunk not found")
    await db.delete(chunk)
    await db.flush()
